### ISSUE TITLE
ebay-filter-menu is not accessible after updating the compoent with new items

### ISSUE THREAD

**Issue by Vaishnavi-Thiyagaraj** [eBay/ebayui-core#1629]
# Bug Report

## Description

Steps to reproduce: 
Render ebay-filter-menu component with 4 items. (say menu1, menu2, menu3 and menu4)
Navigate to menu4 using keyborad and Select menu4.
Replace ebay-filter-menu with new items. (say menu5 and menu6)

Expected: 
With keyboard navigation, first item in ebay-filter-menu should be accessible on tabbing.

Actual: 
ebay-filter-menu items are not accessible with keyboard.

## Workaround

Suggested workaround:
`this.getComponent('filter-menu')._rovingTabIndex.reset();`

This not working because reset is allowed only if the autoReset is enabled and autoReset is configued as null for ebay-filter-menu rovingTabIndex setup. refer(https://github.com/makeup-js/makeup-navigation-emitter/blob/6f7d2d6346c38f2159e51b588f6097896253eda0/src/index.js#L139). The expectation is to expose a method in filter-menu component that reset _rovingTabIndex index to 0, even through autoReset is not set.

## Screenshots

https://user-images.githubusercontent.com/49796069/155211370-6b030949-1a1c-46e1-bf20-e503bca0817e.mov

**Comment by ianmcburnie** [comment]
FYI: link in ticket is to old archived location of makeup. New location is here: https://github.com/makeup/makeup-js/tree/master/packages/makeup-navigation-emitter

**Comment by agliga** [comment]
https://github.com/makeup/makeup-js/pull/64 related PR. That should hopefully fix this issue.

**Comment by agliga** [comment]
Fixed by updating `makeup-roving-tabindex` and `makeup-active-descendant` to the latest

**Comment by Vaishnavi-Thiyagaraj** [comment]
@agliga Would you reopen this bug as the issue is not resolved after the fix, Also as discussed, can you add `resetIndex` method in ebay-filter-menu

```
resetIndex() {
    this._rovingTabIndex.index = 0;
    this.lastTabIndexPosition = 0;
}
```
