### ISSUE TITLE
Button: add support for text wrapping

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#186]

**Comment by ianmcburnie** [comment]
I don't think that our primary and secondary buttons should wrap. Ever. We should choose content that *fits*, and that includes localized text. Look around on GitHub or the desktop OS and see there are no multiline buttons in the UI.

**Comment by seangates** [comment]
I agree. No text wrapping. I believe our design partners would agree.

**Comment by gbeckpdx** [comment]
Agreed. I haven't seen that anywhere nor see it looking great beyond the short intention of the CTA.

**Comment by seangates** [comment]
We won't support text wrapping of buttons.

**Comment by bhoomisatasiya** [comment]
Humm in certain cases it  a little difficult to find smaller text string, just so that it can fit in the button. I think the button should support the wrapping, or reduce the font size and padding. 
Here is an example of three column layout, column 3 has fixed width, 
<img width="1043" alt="screen shot 2018-05-16 at 8 43 08 pm" src="https://user-images.githubusercontent.com/11545472/40155702-09065c20-594a-11e8-8a4b-f1dae3351216.png">
<img width="1080" alt="screen shot 2018-05-16 at 8 43 01 pm" src="https://user-images.githubusercontent.com/11545472/40155704-094f57a4-594a-11e8-93eb-2f12ee11539c.png">

**Comment by ianmcburnie** [comment]
Who is writing the text for these buttons? I hope it's not engineers ;-)

**Comment by ianmcburnie** [comment]
So, after much discussion with content strategists, design and localization teams, we have decided to support text wrapping *only* in the edge-cases where a fixed width has been applied to a button. 

Again though, fixed-width buttons goes against our guidance, and should only be used in specific circumstances, but given that the default behaviour of HTML is to wrap text on fixed width button elements, we should also honour that on our end.

To better illustrate what I mean, imagine the screenshot above with the button text wrapping to two lines alongside the icon button which remains one line. It wont look good.

I will create a ticket in Skin.

**Comment by seangates** [comment]
Resolved via https://github.com/eBay/skin/pull/172.

**Comment by ianmcburnie** [comment]
Reopening as this was not fully resolved. The resolution in skin (referenced in previous comment) truncates the text, but we now want to support wrapping when buttons have a fixed width. We could keep the truncation behaviour available via modifier if we wish.

**Comment by ianmcburnie** [comment]
Skin blocker: https://github.com/eBay/skin/issues/391

**Comment by ianmcburnie** [comment]
Skin buttons have now been refactored to support text wrap by default like native HTML buttons. This breaking change will go into skin v7.0.0, and most likely ebayui v2.0.0.

Closing.
