### ISSUE TITLE
ebay-combobox: device iphone x- clicking on the component - blinking cursor is displayed

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#229]
# Bug Report

## Description
device iphone x- clicking on the ebay-combobox - blinking cursor is displayed
![cursor on combobox](https://user-images.githubusercontent.com/13157115/42057002-cda4bae8-7ad0-11e8-83e1-87c55d7a579b.png)

**Comment by hramakumar** [comment]
This happens in all browsers

**Comment by seangates** [comment]
"all browsers" is pretty broad. In which did you test?

**Comment by hramakumar** [comment]
chrome and safari

**Comment by seangates** [comment]
So, we fixed the cursor issue, but we still need to figure out the collapse part of this issue. Leaving open until that can be figured out.

**Comment by RajaRamu** [comment]
I pulled `ebayui-core@0.8.0` and cursor issue is still there on device. Fix below works only in desktop browsers not on real devices,  
```
text-shadow: 0 0 0 #111820;
color: transparent;
```
This issue is happening in all IOS  and some android devices(safari, chrome and firefox). 
Fix is, 
#1 - change input:text to input:button - https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-combobox/template.marko#L9 
#2 - Adding `text-align:left` in skin/combobox -https://github.com/eBay/skin/blob/master/src/less/combobox/ds6/combobox-base.less#L26

**Comment by seangates** [comment]
It must be a text input for accessibility reasons.

**Comment by msendlakowski** [comment]
Current discussion is to modify this component to have a "readonly" version that uses a button rather than a textbox.  And change the role from "combobox" to "listbox" for a11y.

**Comment by msendlakowski** [comment]
I'm removing this from the milestone.  Applications should use the `ebayui-select` field unless they need the type-ahead feature, which is not available yet.

**Comment by msendlakowski** [comment]
For this release we are recommending that applications use `ebay-select` for mobile and the read-only version of the 'ebay-combobox' only for desktop, which is being updated to avoid the cursor issue.  This strategy will be rethought in a future release.
